[package]
name = "weekend-raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.2"
nalgebra = "0.30.1"
ouroboros = "0.14.0"
rand = "*"
